### ISSUE TITLE
Warning when compiling

### ISSUE THREAD

**Issue by VincentFortinECCC** [mobigroup/sqlite3-dbf#1]
sqlite3-dbf.c:129:2: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
  printf("%s is copyright 2010 Alexey Pechnikov\n");

Hi, very useful tool!
Please note that you forgot to add something at the end of line 129. I suppose you wanted to print the binary name argv[0]?

**Comment by AlexeyPechnikov** [comment]
Thank you, fixed!
